// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw5QAn9ekvumsVXI9N5eOtwaDNHkmBsI0',
    appId: '1:734030590548:web:2186da90035ce58d7cb3c1',
    messagingSenderId: '734030590548',
    projectId: 'chaos2045-f199c',
    authDomain: 'chaos2045-f199c.firebaseapp.com',
    storageBucket: 'chaos2045-f199c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMIOoFyoT5DjUA-zPlfZsSFBS9VZ3TpxM',
    appId: '1:734030590548:android:32faeeba191ad2847cb3c1',
    messagingSenderId: '734030590548',
    projectId: 'chaos2045-f199c',
    storageBucket: 'chaos2045-f199c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARMsSp1fYaK8EK5pnpyndpu5IpxJtX6b8',
    appId: '1:734030590548:ios:31336c65db2623f87cb3c1',
    messagingSenderId: '734030590548',
    projectId: 'chaos2045-f199c',
    storageBucket: 'chaos2045-f199c.firebasestorage.app',
    iosBundleId: 'com.example.shareit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARMsSp1fYaK8EK5pnpyndpu5IpxJtX6b8',
    appId: '1:734030590548:ios:31336c65db2623f87cb3c1',
    messagingSenderId: '734030590548',
    projectId: 'chaos2045-f199c',
    storageBucket: 'chaos2045-f199c.firebasestorage.app',
    iosBundleId: 'com.example.shareit',
  );
}
